#!/opt/bin/sh
# Emit the "Проброс сервисов" overlay for the Detour panel's lighttpd, or nothing.
#
# Same contract (and the same trap) as detour-ssl-helper.sh: lighttpd may execve a
# "simple" include_shell command DIRECTLY, without a shell, and treats a non-zero
# exit as a FATAL config error — which would leave the panel dead. Pointing
# include_shell at this single bare path means a real shell always processes the
# redirect and the `|| true`, so the command exits 0 even before detour-portmap has
# ever written a config.
#
# The file itself is generated by /opt/sbin/detour-portmap (mod_proxy socket blocks
# for every enabled `https` mapping). It is absent until the first published service.
cat /opt/etc/lighttpd/conf.d/detour-portmap.conf 2>/dev/null || true
